### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by DARK7177** [Dark7177/Expense-Tracker#1]
Description 

Implement a dark mode component that would change the theme of the web app upon user request .User should be able to switch between the Dark and light mode on clicking a button 

Default behavior 
![image](https://github.com/user-attachments/assets/23434215-9d79-4711-ab7c-b1cb490017d8)

To reproduce the following just run npm run dev and go to the defined localhost server

**Comment by kunalpal97** [comment]
@Dark7177 check the #PR

**Comment by DARK7177** [comment]
> @Dark7177 check the #PR

Checking sir
